# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.0

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:
.PHONY : .NOTPARALLEL

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/local/bin/cmake

# The command to remove a file.
RM = /opt/local/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/Wqxhouse-Mac/vrproject/CVRPlugins

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/Wqxhouse-Mac/vrproject/CVRPlugins

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/opt/local/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/opt/local/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/opt/local/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/opt/local/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local
.PHONY : install/local/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/opt/local/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	cd /Users/Wqxhouse-Mac/vrproject/CVRPlugins && $(CMAKE_COMMAND) -E cmake_progress_start /Users/Wqxhouse-Mac/vrproject/CVRPlugins/CMakeFiles /Users/Wqxhouse-Mac/vrproject/CVRPlugins/calit2/vrphysics/CMakeFiles/progress.marks
	cd /Users/Wqxhouse-Mac/vrproject/CVRPlugins && $(MAKE) -f CMakeFiles/Makefile2 calit2/vrphysics/all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/Wqxhouse-Mac/vrproject/CVRPlugins/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	cd /Users/Wqxhouse-Mac/vrproject/CVRPlugins && $(MAKE) -f CMakeFiles/Makefile2 calit2/vrphysics/clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	cd /Users/Wqxhouse-Mac/vrproject/CVRPlugins && $(MAKE) -f CMakeFiles/Makefile2 calit2/vrphysics/preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	cd /Users/Wqxhouse-Mac/vrproject/CVRPlugins && $(MAKE) -f CMakeFiles/Makefile2 calit2/vrphysics/preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	cd /Users/Wqxhouse-Mac/vrproject/CVRPlugins && $(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

# Convenience name for target.
calit2/vrphysics/CMakeFiles/vrphysics.dir/rule:
	cd /Users/Wqxhouse-Mac/vrproject/CVRPlugins && $(MAKE) -f CMakeFiles/Makefile2 calit2/vrphysics/CMakeFiles/vrphysics.dir/rule
.PHONY : calit2/vrphysics/CMakeFiles/vrphysics.dir/rule

# Convenience name for target.
vrphysics: calit2/vrphysics/CMakeFiles/vrphysics.dir/rule
.PHONY : vrphysics

# fast build rule for target.
vrphysics/fast:
	cd /Users/Wqxhouse-Mac/vrproject/CVRPlugins && $(MAKE) -f calit2/vrphysics/CMakeFiles/vrphysics.dir/build.make calit2/vrphysics/CMakeFiles/vrphysics.dir/build
.PHONY : vrphysics/fast

Engine/AssetDB.o: Engine/AssetDB.cpp.o
.PHONY : Engine/AssetDB.o

# target to build an object file
Engine/AssetDB.cpp.o:
	cd /Users/Wqxhouse-Mac/vrproject/CVRPlugins && $(MAKE) -f calit2/vrphysics/CMakeFiles/vrphysics.dir/build.make calit2/vrphysics/CMakeFiles/vrphysics.dir/Engine/AssetDB.cpp.o
.PHONY : Engine/AssetDB.cpp.o

Engine/AssetDB.i: Engine/AssetDB.cpp.i
.PHONY : Engine/AssetDB.i

# target to preprocess a source file
Engine/AssetDB.cpp.i:
	cd /Users/Wqxhouse-Mac/vrproject/CVRPlugins && $(MAKE) -f calit2/vrphysics/CMakeFiles/vrphysics.dir/build.make calit2/vrphysics/CMakeFiles/vrphysics.dir/Engine/AssetDB.cpp.i
.PHONY : Engine/AssetDB.cpp.i

Engine/AssetDB.s: Engine/AssetDB.cpp.s
.PHONY : Engine/AssetDB.s

# target to generate assembly for a file
Engine/AssetDB.cpp.s:
	cd /Users/Wqxhouse-Mac/vrproject/CVRPlugins && $(MAKE) -f calit2/vrphysics/CMakeFiles/vrphysics.dir/build.make calit2/vrphysics/CMakeFiles/vrphysics.dir/Engine/AssetDB.cpp.s
.PHONY : Engine/AssetDB.cpp.s

Engine/DirectionalLight.o: Engine/DirectionalLight.cpp.o
.PHONY : Engine/DirectionalLight.o

# target to build an object file
Engine/DirectionalLight.cpp.o:
	cd /Users/Wqxhouse-Mac/vrproject/CVRPlugins && $(MAKE) -f calit2/vrphysics/CMakeFiles/vrphysics.dir/build.make calit2/vrphysics/CMakeFiles/vrphysics.dir/Engine/DirectionalLight.cpp.o
.PHONY : Engine/DirectionalLight.cpp.o

Engine/DirectionalLight.i: Engine/DirectionalLight.cpp.i
.PHONY : Engine/DirectionalLight.i

# target to preprocess a source file
Engine/DirectionalLight.cpp.i:
	cd /Users/Wqxhouse-Mac/vrproject/CVRPlugins && $(MAKE) -f calit2/vrphysics/CMakeFiles/vrphysics.dir/build.make calit2/vrphysics/CMakeFiles/vrphysics.dir/Engine/DirectionalLight.cpp.i
.PHONY : Engine/DirectionalLight.cpp.i

Engine/DirectionalLight.s: Engine/DirectionalLight.cpp.s
.PHONY : Engine/DirectionalLight.s

# target to generate assembly for a file
Engine/DirectionalLight.cpp.s:
	cd /Users/Wqxhouse-Mac/vrproject/CVRPlugins && $(MAKE) -f calit2/vrphysics/CMakeFiles/vrphysics.dir/build.make calit2/vrphysics/CMakeFiles/vrphysics.dir/Engine/DirectionalLight.cpp.s
.PHONY : Engine/DirectionalLight.cpp.s

Engine/DirectionalLightCallback.o: Engine/DirectionalLightCallback.cpp.o
.PHONY : Engine/DirectionalLightCallback.o

# target to build an object file
Engine/DirectionalLightCallback.cpp.o:
	cd /Users/Wqxhouse-Mac/vrproject/CVRPlugins && $(MAKE) -f calit2/vrphysics/CMakeFiles/vrphysics.dir/build.make calit2/vrphysics/CMakeFiles/vrphysics.dir/Engine/DirectionalLightCallback.cpp.o
.PHONY : Engine/DirectionalLightCallback.cpp.o

Engine/DirectionalLightCallback.i: Engine/DirectionalLightCallback.cpp.i
.PHONY : Engine/DirectionalLightCallback.i

# target to preprocess a source file
Engine/DirectionalLightCallback.cpp.i:
	cd /Users/Wqxhouse-Mac/vrproject/CVRPlugins && $(MAKE) -f calit2/vrphysics/CMakeFiles/vrphysics.dir/build.make calit2/vrphysics/CMakeFiles/vrphysics.dir/Engine/DirectionalLightCallback.cpp.i
.PHONY : Engine/DirectionalLightCallback.cpp.i

Engine/DirectionalLightCallback.s: Engine/DirectionalLightCallback.cpp.s
.PHONY : Engine/DirectionalLightCallback.s

# target to generate assembly for a file
Engine/DirectionalLightCallback.cpp.s:
	cd /Users/Wqxhouse-Mac/vrproject/CVRPlugins && $(MAKE) -f calit2/vrphysics/CMakeFiles/vrphysics.dir/build.make calit2/vrphysics/CMakeFiles/vrphysics.dir/Engine/DirectionalLightCallback.cpp.s
.PHONY : Engine/DirectionalLightCallback.cpp.s

Engine/DirectionalLightGroup.o: Engine/DirectionalLightGroup.cpp.o
.PHONY : Engine/DirectionalLightGroup.o

# target to build an object file
Engine/DirectionalLightGroup.cpp.o:
	cd /Users/Wqxhouse-Mac/vrproject/CVRPlugins && $(MAKE) -f calit2/vrphysics/CMakeFiles/vrphysics.dir/build.make calit2/vrphysics/CMakeFiles/vrphysics.dir/Engine/DirectionalLightGroup.cpp.o
.PHONY : Engine/DirectionalLightGroup.cpp.o

Engine/DirectionalLightGroup.i: Engine/DirectionalLightGroup.cpp.i
.PHONY : Engine/DirectionalLightGroup.i

# target to preprocess a source file
Engine/DirectionalLightGroup.cpp.i:
	cd /Users/Wqxhouse-Mac/vrproject/CVRPlugins && $(MAKE) -f calit2/vrphysics/CMakeFiles/vrphysics.dir/build.make calit2/vrphysics/CMakeFiles/vrphysics.dir/Engine/DirectionalLightGroup.cpp.i
.PHONY : Engine/DirectionalLightGroup.cpp.i

Engine/DirectionalLightGroup.s: Engine/DirectionalLightGroup.cpp.s
.PHONY : Engine/DirectionalLightGroup.s

# target to generate assembly for a file
Engine/DirectionalLightGroup.cpp.s:
	cd /Users/Wqxhouse-Mac/vrproject/CVRPlugins && $(MAKE) -f calit2/vrphysics/CMakeFiles/vrphysics.dir/build.make calit2/vrphysics/CMakeFiles/vrphysics.dir/Engine/DirectionalLightGroup.cpp.s
.PHONY : Engine/DirectionalLightGroup.cpp.s

Engine/DirectionalLightingPass.o: Engine/DirectionalLightingPass.cpp.o
.PHONY : Engine/DirectionalLightingPass.o

# target to build an object file
Engine/DirectionalLightingPass.cpp.o:
	cd /Users/Wqxhouse-Mac/vrproject/CVRPlugins && $(MAKE) -f calit2/vrphysics/CMakeFiles/vrphysics.dir/build.make calit2/vrphysics/CMakeFiles/vrphysics.dir/Engine/DirectionalLightingPass.cpp.o
.PHONY : Engine/DirectionalLightingPass.cpp.o

Engine/DirectionalLightingPass.i: Engine/DirectionalLightingPass.cpp.i
.PHONY : Engine/DirectionalLightingPass.i

# target to preprocess a source file
Engine/DirectionalLightingPass.cpp.i:
	cd /Users/Wqxhouse-Mac/vrproject/CVRPlugins && $(MAKE) -f calit2/vrphysics/CMakeFiles/vrphysics.dir/build.make calit2/vrphysics/CMakeFiles/vrphysics.dir/Engine/DirectionalLightingPass.cpp.i
.PHONY : Engine/DirectionalLightingPass.cpp.i

Engine/DirectionalLightingPass.s: Engine/DirectionalLightingPass.cpp.s
.PHONY : Engine/DirectionalLightingPass.s

# target to generate assembly for a file
Engine/DirectionalLightingPass.cpp.s:
	cd /Users/Wqxhouse-Mac/vrproject/CVRPlugins && $(MAKE) -f calit2/vrphysics/CMakeFiles/vrphysics.dir/build.make calit2/vrphysics/CMakeFiles/vrphysics.dir/Engine/DirectionalLightingPass.cpp.s
.PHONY : Engine/DirectionalLightingPass.cpp.s

Engine/FinalPass.o: Engine/FinalPass.cpp.o
.PHONY : Engine/FinalPass.o

# target to build an object file
Engine/FinalPass.cpp.o:
	cd /Users/Wqxhouse-Mac/vrproject/CVRPlugins && $(MAKE) -f calit2/vrphysics/CMakeFiles/vrphysics.dir/build.make calit2/vrphysics/CMakeFiles/vrphysics.dir/Engine/FinalPass.cpp.o
.PHONY : Engine/FinalPass.cpp.o

Engine/FinalPass.i: Engine/FinalPass.cpp.i
.PHONY : Engine/FinalPass.i

# target to preprocess a source file
Engine/FinalPass.cpp.i:
	cd /Users/Wqxhouse-Mac/vrproject/CVRPlugins && $(MAKE) -f calit2/vrphysics/CMakeFiles/vrphysics.dir/build.make calit2/vrphysics/CMakeFiles/vrphysics.dir/Engine/FinalPass.cpp.i
.PHONY : Engine/FinalPass.cpp.i

Engine/FinalPass.s: Engine/FinalPass.cpp.s
.PHONY : Engine/FinalPass.s

# target to generate assembly for a file
Engine/FinalPass.cpp.s:
	cd /Users/Wqxhouse-Mac/vrproject/CVRPlugins && $(MAKE) -f calit2/vrphysics/CMakeFiles/vrphysics.dir/build.make calit2/vrphysics/CMakeFiles/vrphysics.dir/Engine/FinalPass.cpp.s
.PHONY : Engine/FinalPass.cpp.s

Engine/GeometryPass.o: Engine/GeometryPass.cpp.o
.PHONY : Engine/GeometryPass.o

# target to build an object file
Engine/GeometryPass.cpp.o:
	cd /Users/Wqxhouse-Mac/vrproject/CVRPlugins && $(MAKE) -f calit2/vrphysics/CMakeFiles/vrphysics.dir/build.make calit2/vrphysics/CMakeFiles/vrphysics.dir/Engine/GeometryPass.cpp.o
.PHONY : Engine/GeometryPass.cpp.o

Engine/GeometryPass.i: Engine/GeometryPass.cpp.i
.PHONY : Engine/GeometryPass.i

# target to preprocess a source file
Engine/GeometryPass.cpp.i:
	cd /Users/Wqxhouse-Mac/vrproject/CVRPlugins && $(MAKE) -f calit2/vrphysics/CMakeFiles/vrphysics.dir/build.make calit2/vrphysics/CMakeFiles/vrphysics.dir/Engine/GeometryPass.cpp.i
.PHONY : Engine/GeometryPass.cpp.i

Engine/GeometryPass.s: Engine/GeometryPass.cpp.s
.PHONY : Engine/GeometryPass.s

# target to generate assembly for a file
Engine/GeometryPass.cpp.s:
	cd /Users/Wqxhouse-Mac/vrproject/CVRPlugins && $(MAKE) -f calit2/vrphysics/CMakeFiles/vrphysics.dir/build.make calit2/vrphysics/CMakeFiles/vrphysics.dir/Engine/GeometryPass.cpp.s
.PHONY : Engine/GeometryPass.cpp.s

Engine/LightCallback.o: Engine/LightCallback.cpp.o
.PHONY : Engine/LightCallback.o

# target to build an object file
Engine/LightCallback.cpp.o:
	cd /Users/Wqxhouse-Mac/vrproject/CVRPlugins && $(MAKE) -f calit2/vrphysics/CMakeFiles/vrphysics.dir/build.make calit2/vrphysics/CMakeFiles/vrphysics.dir/Engine/LightCallback.cpp.o
.PHONY : Engine/LightCallback.cpp.o

Engine/LightCallback.i: Engine/LightCallback.cpp.i
.PHONY : Engine/LightCallback.i

# target to preprocess a source file
Engine/LightCallback.cpp.i:
	cd /Users/Wqxhouse-Mac/vrproject/CVRPlugins && $(MAKE) -f calit2/vrphysics/CMakeFiles/vrphysics.dir/build.make calit2/vrphysics/CMakeFiles/vrphysics.dir/Engine/LightCallback.cpp.i
.PHONY : Engine/LightCallback.cpp.i

Engine/LightCallback.s: Engine/LightCallback.cpp.s
.PHONY : Engine/LightCallback.s

# target to generate assembly for a file
Engine/LightCallback.cpp.s:
	cd /Users/Wqxhouse-Mac/vrproject/CVRPlugins && $(MAKE) -f calit2/vrphysics/CMakeFiles/vrphysics.dir/build.make calit2/vrphysics/CMakeFiles/vrphysics.dir/Engine/LightCallback.cpp.s
.PHONY : Engine/LightCallback.cpp.s

Engine/LightGroup.o: Engine/LightGroup.cpp.o
.PHONY : Engine/LightGroup.o

# target to build an object file
Engine/LightGroup.cpp.o:
	cd /Users/Wqxhouse-Mac/vrproject/CVRPlugins && $(MAKE) -f calit2/vrphysics/CMakeFiles/vrphysics.dir/build.make calit2/vrphysics/CMakeFiles/vrphysics.dir/Engine/LightGroup.cpp.o
.PHONY : Engine/LightGroup.cpp.o

Engine/LightGroup.i: Engine/LightGroup.cpp.i
.PHONY : Engine/LightGroup.i

# target to preprocess a source file
Engine/LightGroup.cpp.i:
	cd /Users/Wqxhouse-Mac/vrproject/CVRPlugins && $(MAKE) -f calit2/vrphysics/CMakeFiles/vrphysics.dir/build.make calit2/vrphysics/CMakeFiles/vrphysics.dir/Engine/LightGroup.cpp.i
.PHONY : Engine/LightGroup.cpp.i

Engine/LightGroup.s: Engine/LightGroup.cpp.s
.PHONY : Engine/LightGroup.s

# target to generate assembly for a file
Engine/LightGroup.cpp.s:
	cd /Users/Wqxhouse-Mac/vrproject/CVRPlugins && $(MAKE) -f calit2/vrphysics/CMakeFiles/vrphysics.dir/build.make calit2/vrphysics/CMakeFiles/vrphysics.dir/Engine/LightGroup.cpp.s
.PHONY : Engine/LightGroup.cpp.s

Engine/LightGroupAnimationCallback.o: Engine/LightGroupAnimationCallback.cpp.o
.PHONY : Engine/LightGroupAnimationCallback.o

# target to build an object file
Engine/LightGroupAnimationCallback.cpp.o:
	cd /Users/Wqxhouse-Mac/vrproject/CVRPlugins && $(MAKE) -f calit2/vrphysics/CMakeFiles/vrphysics.dir/build.make calit2/vrphysics/CMakeFiles/vrphysics.dir/Engine/LightGroupAnimationCallback.cpp.o
.PHONY : Engine/LightGroupAnimationCallback.cpp.o

Engine/LightGroupAnimationCallback.i: Engine/LightGroupAnimationCallback.cpp.i
.PHONY : Engine/LightGroupAnimationCallback.i

# target to preprocess a source file
Engine/LightGroupAnimationCallback.cpp.i:
	cd /Users/Wqxhouse-Mac/vrproject/CVRPlugins && $(MAKE) -f calit2/vrphysics/CMakeFiles/vrphysics.dir/build.make calit2/vrphysics/CMakeFiles/vrphysics.dir/Engine/LightGroupAnimationCallback.cpp.i
.PHONY : Engine/LightGroupAnimationCallback.cpp.i

Engine/LightGroupAnimationCallback.s: Engine/LightGroupAnimationCallback.cpp.s
.PHONY : Engine/LightGroupAnimationCallback.s

# target to generate assembly for a file
Engine/LightGroupAnimationCallback.cpp.s:
	cd /Users/Wqxhouse-Mac/vrproject/CVRPlugins && $(MAKE) -f calit2/vrphysics/CMakeFiles/vrphysics.dir/build.make calit2/vrphysics/CMakeFiles/vrphysics.dir/Engine/LightGroupAnimationCallback.cpp.s
.PHONY : Engine/LightGroupAnimationCallback.cpp.s

Engine/LightingPass.o: Engine/LightingPass.cpp.o
.PHONY : Engine/LightingPass.o

# target to build an object file
Engine/LightingPass.cpp.o:
	cd /Users/Wqxhouse-Mac/vrproject/CVRPlugins && $(MAKE) -f calit2/vrphysics/CMakeFiles/vrphysics.dir/build.make calit2/vrphysics/CMakeFiles/vrphysics.dir/Engine/LightingPass.cpp.o
.PHONY : Engine/LightingPass.cpp.o

Engine/LightingPass.i: Engine/LightingPass.cpp.i
.PHONY : Engine/LightingPass.i

# target to preprocess a source file
Engine/LightingPass.cpp.i:
	cd /Users/Wqxhouse-Mac/vrproject/CVRPlugins && $(MAKE) -f calit2/vrphysics/CMakeFiles/vrphysics.dir/build.make calit2/vrphysics/CMakeFiles/vrphysics.dir/Engine/LightingPass.cpp.i
.PHONY : Engine/LightingPass.cpp.i

Engine/LightingPass.s: Engine/LightingPass.cpp.s
.PHONY : Engine/LightingPass.s

# target to generate assembly for a file
Engine/LightingPass.cpp.s:
	cd /Users/Wqxhouse-Mac/vrproject/CVRPlugins && $(MAKE) -f calit2/vrphysics/CMakeFiles/vrphysics.dir/build.make calit2/vrphysics/CMakeFiles/vrphysics.dir/Engine/LightingPass.cpp.s
.PHONY : Engine/LightingPass.cpp.s

Engine/Material.o: Engine/Material.cpp.o
.PHONY : Engine/Material.o

# target to build an object file
Engine/Material.cpp.o:
	cd /Users/Wqxhouse-Mac/vrproject/CVRPlugins && $(MAKE) -f calit2/vrphysics/CMakeFiles/vrphysics.dir/build.make calit2/vrphysics/CMakeFiles/vrphysics.dir/Engine/Material.cpp.o
.PHONY : Engine/Material.cpp.o

Engine/Material.i: Engine/Material.cpp.i
.PHONY : Engine/Material.i

# target to preprocess a source file
Engine/Material.cpp.i:
	cd /Users/Wqxhouse-Mac/vrproject/CVRPlugins && $(MAKE) -f calit2/vrphysics/CMakeFiles/vrphysics.dir/build.make calit2/vrphysics/CMakeFiles/vrphysics.dir/Engine/Material.cpp.i
.PHONY : Engine/Material.cpp.i

Engine/Material.s: Engine/Material.cpp.s
.PHONY : Engine/Material.s

# target to generate assembly for a file
Engine/Material.cpp.s:
	cd /Users/Wqxhouse-Mac/vrproject/CVRPlugins && $(MAKE) -f calit2/vrphysics/CMakeFiles/vrphysics.dir/build.make calit2/vrphysics/CMakeFiles/vrphysics.dir/Engine/Material.cpp.s
.PHONY : Engine/Material.cpp.s

Engine/PointLight.o: Engine/PointLight.cpp.o
.PHONY : Engine/PointLight.o

# target to build an object file
Engine/PointLight.cpp.o:
	cd /Users/Wqxhouse-Mac/vrproject/CVRPlugins && $(MAKE) -f calit2/vrphysics/CMakeFiles/vrphysics.dir/build.make calit2/vrphysics/CMakeFiles/vrphysics.dir/Engine/PointLight.cpp.o
.PHONY : Engine/PointLight.cpp.o

Engine/PointLight.i: Engine/PointLight.cpp.i
.PHONY : Engine/PointLight.i

# target to preprocess a source file
Engine/PointLight.cpp.i:
	cd /Users/Wqxhouse-Mac/vrproject/CVRPlugins && $(MAKE) -f calit2/vrphysics/CMakeFiles/vrphysics.dir/build.make calit2/vrphysics/CMakeFiles/vrphysics.dir/Engine/PointLight.cpp.i
.PHONY : Engine/PointLight.cpp.i

Engine/PointLight.s: Engine/PointLight.cpp.s
.PHONY : Engine/PointLight.s

# target to generate assembly for a file
Engine/PointLight.cpp.s:
	cd /Users/Wqxhouse-Mac/vrproject/CVRPlugins && $(MAKE) -f calit2/vrphysics/CMakeFiles/vrphysics.dir/build.make calit2/vrphysics/CMakeFiles/vrphysics.dir/Engine/PointLight.cpp.s
.PHONY : Engine/PointLight.cpp.s

Engine/SSAOPass.o: Engine/SSAOPass.cpp.o
.PHONY : Engine/SSAOPass.o

# target to build an object file
Engine/SSAOPass.cpp.o:
	cd /Users/Wqxhouse-Mac/vrproject/CVRPlugins && $(MAKE) -f calit2/vrphysics/CMakeFiles/vrphysics.dir/build.make calit2/vrphysics/CMakeFiles/vrphysics.dir/Engine/SSAOPass.cpp.o
.PHONY : Engine/SSAOPass.cpp.o

Engine/SSAOPass.i: Engine/SSAOPass.cpp.i
.PHONY : Engine/SSAOPass.i

# target to preprocess a source file
Engine/SSAOPass.cpp.i:
	cd /Users/Wqxhouse-Mac/vrproject/CVRPlugins && $(MAKE) -f calit2/vrphysics/CMakeFiles/vrphysics.dir/build.make calit2/vrphysics/CMakeFiles/vrphysics.dir/Engine/SSAOPass.cpp.i
.PHONY : Engine/SSAOPass.cpp.i

Engine/SSAOPass.s: Engine/SSAOPass.cpp.s
.PHONY : Engine/SSAOPass.s

# target to generate assembly for a file
Engine/SSAOPass.cpp.s:
	cd /Users/Wqxhouse-Mac/vrproject/CVRPlugins && $(MAKE) -f calit2/vrphysics/CMakeFiles/vrphysics.dir/build.make calit2/vrphysics/CMakeFiles/vrphysics.dir/Engine/SSAOPass.cpp.s
.PHONY : Engine/SSAOPass.cpp.s

Engine/ScreenPass.o: Engine/ScreenPass.cpp.o
.PHONY : Engine/ScreenPass.o

# target to build an object file
Engine/ScreenPass.cpp.o:
	cd /Users/Wqxhouse-Mac/vrproject/CVRPlugins && $(MAKE) -f calit2/vrphysics/CMakeFiles/vrphysics.dir/build.make calit2/vrphysics/CMakeFiles/vrphysics.dir/Engine/ScreenPass.cpp.o
.PHONY : Engine/ScreenPass.cpp.o

Engine/ScreenPass.i: Engine/ScreenPass.cpp.i
.PHONY : Engine/ScreenPass.i

# target to preprocess a source file
Engine/ScreenPass.cpp.i:
	cd /Users/Wqxhouse-Mac/vrproject/CVRPlugins && $(MAKE) -f calit2/vrphysics/CMakeFiles/vrphysics.dir/build.make calit2/vrphysics/CMakeFiles/vrphysics.dir/Engine/ScreenPass.cpp.i
.PHONY : Engine/ScreenPass.cpp.i

Engine/ScreenPass.s: Engine/ScreenPass.cpp.s
.PHONY : Engine/ScreenPass.s

# target to generate assembly for a file
Engine/ScreenPass.cpp.s:
	cd /Users/Wqxhouse-Mac/vrproject/CVRPlugins && $(MAKE) -f calit2/vrphysics/CMakeFiles/vrphysics.dir/build.make calit2/vrphysics/CMakeFiles/vrphysics.dir/Engine/ScreenPass.cpp.s
.PHONY : Engine/ScreenPass.cpp.s

Engine/Shared.o: Engine/Shared.cpp.o
.PHONY : Engine/Shared.o

# target to build an object file
Engine/Shared.cpp.o:
	cd /Users/Wqxhouse-Mac/vrproject/CVRPlugins && $(MAKE) -f calit2/vrphysics/CMakeFiles/vrphysics.dir/build.make calit2/vrphysics/CMakeFiles/vrphysics.dir/Engine/Shared.cpp.o
.PHONY : Engine/Shared.cpp.o

Engine/Shared.i: Engine/Shared.cpp.i
.PHONY : Engine/Shared.i

# target to preprocess a source file
Engine/Shared.cpp.i:
	cd /Users/Wqxhouse-Mac/vrproject/CVRPlugins && $(MAKE) -f calit2/vrphysics/CMakeFiles/vrphysics.dir/build.make calit2/vrphysics/CMakeFiles/vrphysics.dir/Engine/Shared.cpp.i
.PHONY : Engine/Shared.cpp.i

Engine/Shared.s: Engine/Shared.cpp.s
.PHONY : Engine/Shared.s

# target to generate assembly for a file
Engine/Shared.cpp.s:
	cd /Users/Wqxhouse-Mac/vrproject/CVRPlugins && $(MAKE) -f calit2/vrphysics/CMakeFiles/vrphysics.dir/build.make calit2/vrphysics/CMakeFiles/vrphysics.dir/Engine/Shared.cpp.s
.PHONY : Engine/Shared.cpp.s

Engine/Utils.o: Engine/Utils.cpp.o
.PHONY : Engine/Utils.o

# target to build an object file
Engine/Utils.cpp.o:
	cd /Users/Wqxhouse-Mac/vrproject/CVRPlugins && $(MAKE) -f calit2/vrphysics/CMakeFiles/vrphysics.dir/build.make calit2/vrphysics/CMakeFiles/vrphysics.dir/Engine/Utils.cpp.o
.PHONY : Engine/Utils.cpp.o

Engine/Utils.i: Engine/Utils.cpp.i
.PHONY : Engine/Utils.i

# target to preprocess a source file
Engine/Utils.cpp.i:
	cd /Users/Wqxhouse-Mac/vrproject/CVRPlugins && $(MAKE) -f calit2/vrphysics/CMakeFiles/vrphysics.dir/build.make calit2/vrphysics/CMakeFiles/vrphysics.dir/Engine/Utils.cpp.i
.PHONY : Engine/Utils.cpp.i

Engine/Utils.s: Engine/Utils.cpp.s
.PHONY : Engine/Utils.s

# target to generate assembly for a file
Engine/Utils.cpp.s:
	cd /Users/Wqxhouse-Mac/vrproject/CVRPlugins && $(MAKE) -f calit2/vrphysics/CMakeFiles/vrphysics.dir/build.make calit2/vrphysics/CMakeFiles/vrphysics.dir/Engine/Utils.cpp.s
.PHONY : Engine/Utils.cpp.s

PhysicsLabZW.o: PhysicsLabZW.cpp.o
.PHONY : PhysicsLabZW.o

# target to build an object file
PhysicsLabZW.cpp.o:
	cd /Users/Wqxhouse-Mac/vrproject/CVRPlugins && $(MAKE) -f calit2/vrphysics/CMakeFiles/vrphysics.dir/build.make calit2/vrphysics/CMakeFiles/vrphysics.dir/PhysicsLabZW.cpp.o
.PHONY : PhysicsLabZW.cpp.o

PhysicsLabZW.i: PhysicsLabZW.cpp.i
.PHONY : PhysicsLabZW.i

# target to preprocess a source file
PhysicsLabZW.cpp.i:
	cd /Users/Wqxhouse-Mac/vrproject/CVRPlugins && $(MAKE) -f calit2/vrphysics/CMakeFiles/vrphysics.dir/build.make calit2/vrphysics/CMakeFiles/vrphysics.dir/PhysicsLabZW.cpp.i
.PHONY : PhysicsLabZW.cpp.i

PhysicsLabZW.s: PhysicsLabZW.cpp.s
.PHONY : PhysicsLabZW.s

# target to generate assembly for a file
PhysicsLabZW.cpp.s:
	cd /Users/Wqxhouse-Mac/vrproject/CVRPlugins && $(MAKE) -f calit2/vrphysics/CMakeFiles/vrphysics.dir/build.make calit2/vrphysics/CMakeFiles/vrphysics.dir/PhysicsLabZW.cpp.s
.PHONY : PhysicsLabZW.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... vrphysics"
	@echo "... Engine/AssetDB.o"
	@echo "... Engine/AssetDB.i"
	@echo "... Engine/AssetDB.s"
	@echo "... Engine/DirectionalLight.o"
	@echo "... Engine/DirectionalLight.i"
	@echo "... Engine/DirectionalLight.s"
	@echo "... Engine/DirectionalLightCallback.o"
	@echo "... Engine/DirectionalLightCallback.i"
	@echo "... Engine/DirectionalLightCallback.s"
	@echo "... Engine/DirectionalLightGroup.o"
	@echo "... Engine/DirectionalLightGroup.i"
	@echo "... Engine/DirectionalLightGroup.s"
	@echo "... Engine/DirectionalLightingPass.o"
	@echo "... Engine/DirectionalLightingPass.i"
	@echo "... Engine/DirectionalLightingPass.s"
	@echo "... Engine/FinalPass.o"
	@echo "... Engine/FinalPass.i"
	@echo "... Engine/FinalPass.s"
	@echo "... Engine/GeometryPass.o"
	@echo "... Engine/GeometryPass.i"
	@echo "... Engine/GeometryPass.s"
	@echo "... Engine/LightCallback.o"
	@echo "... Engine/LightCallback.i"
	@echo "... Engine/LightCallback.s"
	@echo "... Engine/LightGroup.o"
	@echo "... Engine/LightGroup.i"
	@echo "... Engine/LightGroup.s"
	@echo "... Engine/LightGroupAnimationCallback.o"
	@echo "... Engine/LightGroupAnimationCallback.i"
	@echo "... Engine/LightGroupAnimationCallback.s"
	@echo "... Engine/LightingPass.o"
	@echo "... Engine/LightingPass.i"
	@echo "... Engine/LightingPass.s"
	@echo "... Engine/Material.o"
	@echo "... Engine/Material.i"
	@echo "... Engine/Material.s"
	@echo "... Engine/PointLight.o"
	@echo "... Engine/PointLight.i"
	@echo "... Engine/PointLight.s"
	@echo "... Engine/SSAOPass.o"
	@echo "... Engine/SSAOPass.i"
	@echo "... Engine/SSAOPass.s"
	@echo "... Engine/ScreenPass.o"
	@echo "... Engine/ScreenPass.i"
	@echo "... Engine/ScreenPass.s"
	@echo "... Engine/Shared.o"
	@echo "... Engine/Shared.i"
	@echo "... Engine/Shared.s"
	@echo "... Engine/Utils.o"
	@echo "... Engine/Utils.i"
	@echo "... Engine/Utils.s"
	@echo "... PhysicsLabZW.o"
	@echo "... PhysicsLabZW.i"
	@echo "... PhysicsLabZW.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	cd /Users/Wqxhouse-Mac/vrproject/CVRPlugins && $(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

